// app/echo/report/page.tsx
import { prisma } from "@/lib/prisma";
import { temperature, status } from "@/lib/temperature";

export const dynamic = "force-dynamic";

export default async function ReportPage() {
  const contacts = await prisma.contact.findMany({ where: { archived: false } });
  const icebreakers = await prisma.icebreaker.findMany({});

  const stats = { warm: 0, cool: 0, frozen: 0 };
  contacts.forEach((c) => {
    const s = status(temperature(c.level, c.lastContact));
    stats[s]++;
  });
  const total = contacts.length || 1;
  const used = icebreakers.filter((i) => i.used).length;
  const ignored = icebreakers.filter((i) => i.ignored).length;
  const archivedCount = await prisma.contact.count({ where: { archived: true } });

  // 能量分：暖色占比 60% + 已使用破冰 30% + (1 - 忽略率) 10%
  const warmRate = stats.warm / total;
  const useRate = icebreakers.length > 0 ? used / icebreakers.length : 0.5;
  const ignoreRate = icebreakers.length > 0 ? ignored / icebreakers.length : 0;
  const energy = Math.round(
    (warmRate * 0.6 + useRate * 0.3 + (1 - ignoreRate) * 0.1) * 100
  );

  return (
    <div className="space-y-6">
      <h2 className="text-2xl font-bold">⚡ 社交能量报告</h2>

      <div className="card p-8 flex flex-col items-center">
        <div className="relative w-48 h-48">
          <svg viewBox="0 0 100 100" className="w-full h-full -rotate-90">
            <circle cx="50" cy="50" r="42" stroke="#eee" strokeWidth="10" fill="none" />
            <circle
              cx="50" cy="50" r="42"
              stroke="#FFB07A" strokeWidth="10" fill="none"
              strokeLinecap="round"
              strokeDasharray={`${(energy / 100) * 264} 264`}
            />
          </svg>
          <div className="absolute inset-0 flex flex-col items-center justify-center">
            <div className="text-5xl font-bold">{energy}</div>
            <div className="text-xs text-black/50 mt-1">本周能量</div>
          </div>
        </div>
        <p className="mt-6 text-sm text-black/60 text-center max-w-md">
          {energy >= 70
            ? "你这周维护了很多重要的关系，继续保持~"
            : energy >= 40
            ? "有一些联系人正在降温，找几个顺手的理由聊聊吧。"
            : "通讯录里很多关系正在结冰，但别有压力——挑你最想维护的开始就好。"}
        </p>
      </div>

      <div className="grid sm:grid-cols-3 gap-4">
        <Stat label="🔥 温热" value={stats.warm} total={total} color="bg-orange-400" />
        <Stat label="🌤 常温" value={stats.cool} total={total} color="bg-slate-400" />
        <Stat label="❄️ 结冰" value={stats.frozen} total={total} color="bg-blue-400" />
      </div>

      <div className="grid sm:grid-cols-3 gap-4">
        <Mini label="生成的破冰建议" value={icebreakers.length} />
        <Mini label="实际使用" value={used} />
        <Mini label="自然沉淀" value={archivedCount} />
      </div>
    </div>
  );
}

function Stat({ label, value, total, color }: any) {
  const ratio = total === 0 ? 0 : (value / total) * 100;
  return (
    <div className="card p-5">
      <div className="text-sm text-black/60">{label}</div>
      <div className="text-3xl font-bold mt-1">{value}</div>
      <div className="mt-3 h-1.5 rounded-full bg-black/5 overflow-hidden">
        <div className={`h-full ${color}`} style={{ width: `${ratio}%` }} />
      </div>
    </div>
  );
}

function Mini({ label, value }: any) {
  return (
    <div className="card p-5 text-center">
      <div className="text-3xl font-bold">{value}</div>
      <div className="text-xs text-black/50 mt-1">{label}</div>
    </div>
  );
}

// 中保真/src/views/Report.vue
<template>
  <div class="col" style="gap:16px">
    <h2 class="title">社交能量报告</h2>

    <!-- 能量环 -->
    <div class="box energy-ring" style="padding:30px">
      <svg viewBox="0 0 100 100" width="160" height="160" style="transform:rotate(-90deg)">
        <circle cx="50" cy="50" r="42" stroke="#e8e8e8" stroke-width="8" fill="none" />
        <circle cx="50" cy="50" r="42" stroke="#888" stroke-width="8" fill="none"
          stroke-linecap="round" :stroke-dasharray="`${(energy / 100) * 264} 264`" />
      </svg>
      <div style="margin-top:-110px">
        <div class="energy-num">{{ energy }}</div>
        <div class="muted" style="text-align:center">本周能量</div>
      </div>
      <div style="margin-top:80px; max-width:400px; text-align:center; color:#555; line-height:1.7">
        {{ energyText }}
      </div>
    </div>

    <!-- 温度分布 -->
    <div class="section-title">— 温度分布 —</div>
    <div class="grid">
      <div class="box">
        <div class="muted">温热</div>
        <div style="font-size:24px; font-weight:600; margin:4px 0">{{ stats.warm }}</div>
        <div class="bar"><div class="bar-fill warm" :style="{ width: ratio(stats.warm) + '%' }" /></div>
      </div>
      <div class="box">
        <div class="muted">常温</div>
        <div style="font-size:24px; font-weight:600; margin:4px 0">{{ stats.cool }}</div>
        <div class="bar"><div class="bar-fill cool" :style="{ width: ratio(stats.cool) + '%' }" /></div>
      </div>
      <div class="box">
        <div class="muted">结冰</div>
        <div style="font-size:24px; font-weight:600; margin:4px 0">{{ stats.frozen }}</div>
        <div class="bar"><div class="bar-fill frozen" :style="{ width: ratio(stats.frozen) + '%' }" /></div>
      </div>
    </div>

    <!-- 互动统计 -->
    <div class="section-title">— 互动统计 —</div>
    <div class="grid">
      <div class="box" style="text-align:center">
        <div style="font-size:24px; font-weight:600">{{ totalIcebreakers }}</div>
        <div class="muted">生成的破冰建议</div>
      </div>
      <div class="box" style="text-align:center">
        <div style="font-size:24px; font-weight:600">{{ usedCount }}</div>
        <div class="muted">实际使用</div>
      </div>
      <div class="box" style="text-align:center">
        <div style="font-size:24px; font-weight:600">{{ archivedCount }}</div>
        <div class="muted">自然沉淀</div>
      </div>
    </div>
  </div>
</template>

<script setup>
import { computed } from "vue";
import { store } from "../store.js";
import { temperature, statusOf } from "../utils.js";

const active = computed(() => store.contacts.filter((c) => !c.archived));
const stats = computed(() => {
  const s = { warm: 0, cool: 0, frozen: 0 };
  active.value.forEach((c) => s[statusOf(temperature(c.level, c.lastContact))]++);
  return s;
});
const total = computed(() => active.value.length || 1);
function ratio(v) { return (v / total.value) * 100; }

const allHistory = computed(() => store.contacts.flatMap((c) => c.history.filter((h) => h.drafts)));
const totalIcebreakers = computed(() => allHistory.value.length);
const usedCount = computed(() => allHistory.value.filter((h) => h.used).length);
const ignoredCount = computed(() => allHistory.value.filter((h) => h.ignored).length);
const archivedCount = computed(() => store.contacts.filter((c) => c.archived).length);

const energy = computed(() => {
  const warmRate = stats.value.warm / total.value;
  const useRate = totalIcebreakers.value > 0 ? usedCount.value / totalIcebreakers.value : 0.5;
  const ignoreRate = totalIcebreakers.value > 0 ? ignoredCount.value / totalIcebreakers.value : 0;
  return Math.round((warmRate * 0.6 + useRate * 0.3 + (1 - ignoreRate) * 0.1) * 100);
});
const energyText = computed(() => {
  if (energy.value >= 70) return "你这周维护了很多重要的关系，继续保持~";
  if (energy.value >= 40) return "有一些联系人正在降温，找几个顺手的理由聊聊吧。";
  return "通讯录里很多关系正在结冰，但别有压力——挑你最想维护的开始就好。";
});
</script>
